#!/usr/bin/env bash

echo APP_NAME=$APP_NAME
echo APP_COLOR=$APP_COLOR

SERVER_PORT=$(node ./scripts/find-open-port)
API_SERVER="http://localhost:${SERVER_PORT}"

echo "API_SERVER=${API_SERVER}"

exec concurrently \
  --kill-others \
  --names "SERVER,CLIENT" \
  "PORT=${SERVER_PORT} nodemon ./server.js" \
  "cd client && BROWSER=none DANGEROUSLY_DISABLE_HOST_CHECK=true API_SERVER=\"${API_SERVER}\" npm run start"

