#!/usr/bin/env bash

export NODE_ENV=development
SERVER_PORT=$(node ./scripts/find-open-port.js)
API_SERVER="http://localhost:${SERVER_PORT}"

exec concurrently \
  --kill-others \
  --names "SERVER,CLIENT" \
  "PORT=${SERVER_PORT} nodemon --exec ./scripts/start.cjs" \
  "cd client && BROWSER=none DANGEROUSLY_DISABLE_HOST_CHECK=true API_SERVER=\"${API_SERVER}\" npm run start"

