#!/usr/bin/env bash

START_CMD="./scripts/dev-start"

export NODE_TLS_REJECT_UNAUTHORIZED='0'

exec concurrently \
  --kill-others \
  --names "cat-walkers,bad-birders,dope-dogs" \
  "dotenv -e ./dev/cat-walkers/env ${START_CMD}" \
  "dotenv -e ./dev/bad-birders/env ${START_CMD}" \
  "dotenv -e ./dev/dope-dogs/env ${START_CMD}"
